apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-watcher
subjects:
- kind: ServiceAccount
  name: namespace-watcher
  namespace: ns-monitoring
roleRef:
  kind: ClusterRole
  name: namespace-watcher
  apiGroup: rbac.authorization.k8s.io